<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;

class UserData extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data User
        $user = [
            [
                'nama' => 'Administrator',
                'username' => 'admin',
                'password' => bcrypt('12345'),
                'role' => 'Admin',
                'id_jabatan' => 1,
            ],
            [
                'nama' => 'Dekan Pascasarjana',
                'username' => 'dekan.pascasarjana',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 2,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Dekan Kedokteran',
                'username' => 'dekan.fk',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 4,
                'id_fakultas' => 2,
            ],
            [
                'nama' => 'Dekan Kedokteran Gigi',
                'username' => 'dekan.fkg',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 6,
                'id_fakultas' => 3,
            ],
            [
                'nama' => 'Dekan Teknologi Informasi',
                'username' => 'dekan.fti',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 8,
                'id_fakultas' => 4,
            ],
            [
                'nama' => 'Dekan Ekonomi dan Bisnis',
                'username' => 'dekan.feb',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 10,
                'id_fakultas' => 5,
            ],
            [
                'nama' => 'Dekan Hukum',
                'username' => 'dekan.fh',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 12,
                'id_fakultas' => 6,
            ],
            [
                'nama' => 'Dekan Psikologi',
                'username' => 'dekan.psi',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 14,
                'id_fakultas' => 7,
            ],
            [
                'nama' => 'Wadek 1 Pascasarjana',
                'username' => 'wadek1.pascasarjana',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 3,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Wadek 1 Kedokteran',
                'username' => 'wadek1.fk',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 5,
                'id_fakultas' => 2,
            ],
            [
                'nama' => 'Wadek 1 Kedokteran Gigi',
                'username' => 'wadek1.fkg',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 7,
                'id_fakultas' => 3,
            ],
            [
                'nama' => 'Wadek 1 Teknologi Informasi',
                'username' => 'wadek1.fti',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 9,
                'id_fakultas' => 4,
            ],
            [
                'nama' => 'Wadek 1 Ekonomi dan Bisnis',
                'username' => 'wadek1.feb',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 11,
                'id_fakultas' => 5,
            ],
            [
                'nama' => 'Wadek 1 Hukum',
                'username' => 'wadek1.fh',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 13,
                'id_fakultas' => 6,
            ],
            [
                'nama' => 'Wadek 1 Psikologi',
                'username' => 'wadek1.psi',
                'password' => bcrypt('12345'),
                'role' => 'Dekanat Fakultas',
                'id_jabatan' => 15,
                'id_fakultas' => 7,
            ],
            [
                'nama' => 'Tendik Pascasarjana',
                'username' => 'tendik.pascasarjana',
                'password' => bcrypt('12345'),
                'role' => 'Tendik',
                'id_jabatan' => 16,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Tendik Kedokteran',
                'username' => 'tendik.fk',
                'password' => bcrypt('12345'),
                'role' => 'Tendik',
                'id_jabatan' => 17,
                'id_fakultas' => 2,
            ],
            [
                'nama' => 'Tendik Kedokteran Gigi',
                'username' => 'tendik.fkg',
                'password' => bcrypt('12345'),
                'role' => 'Tendik',
                'id_jabatan' => 18,
                'id_fakultas' => 3,
            ],
            [
                'nama' => 'Tendik Teknologi Informasi',
                'username' => 'tendik.ti',
                'password' => bcrypt('12345'),
                'role' => 'Tendik',
                'id_jabatan' => 19,
                'id_fakultas' => 4,
            ],
            [
                'nama' => 'Tendik Ekonomi dan Bisnis',
                'username' => 'tendik.feb',
                'password' => bcrypt('12345'),
                'role' => 'Tendik',
                'id_jabatan' => 20,
                'id_fakultas' => 5,
            ],
            [
                'nama' => 'Tendik Hukum',
                'username' => 'tendik.fh',
                'password' => bcrypt('12345'),
                'role' => 'Tendik',
                'id_jabatan' => 21,
                'id_fakultas' => 6,
            ],
            [
                'nama' => 'Tendik Psikologi',
                'username' => 'tendik.psi',
                'password' => bcrypt('12345'),
                'role' => 'Tendik',
                'id_jabatan' => 22,
                'id_fakultas' => 7,
            ],
            [
                'nama' => 'Kaprodi Magister Kenotariatan',
                'username' => 'kaprodi.mk',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 23,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Kaprodi Magister Manajemen',
                'username' => 'kaprodi.mm',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 25,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Kaprodi Magister Sains Biomedis',
                'username' => 'kaprodi.msb',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 27,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Kaprodi Magister Administrasi Rumah Sakit',
                'username' => 'kaprodi.mars',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 29,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Kaprodi Doktor Sains Biomedis',
                'username' => 'kaprodi.dsb',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 31,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Kaprodi Kedokteran',
                'username' => 'kaprodi.fk',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 33,
                'id_fakultas' => 2,
            ],
            [
                'nama' => 'Kaprodi Pendidikan Profesi Kedokteran',
                'username' => 'kaprodi.fkp',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 35,
                'id_fakultas' => 2,
            ],
            [
                'nama' => 'Kaprodi Kedokteran Gigi',
                'username' => 'kaprodi.fkg',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 37,
                'id_fakultas' => 3,
            ],
            [
                'nama' => 'Kaprodi Kedokteran Gigi Program Profesi',
                'username' => 'kaprodi.fkgp',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 39,
                'id_fakultas' => 3,
            ],
            [
                'nama' => 'Kaprodi Teknik Informatika',
                'username' => 'kaprodi.ti',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 41,
                'id_fakultas' => 4,
            ],
            [
                'nama' => 'Kaprodi Ilmu Perpustakaan',
                'username' => 'kaprodi.ip',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 43,
                'id_fakultas' => 4,
            ],
            [
                'nama' => 'Kaprodi Manajemen',
                'username' => 'kaprodi.mnj',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 45,
                'id_fakultas' => 5,
            ],
            [
                'nama' => 'Kaprodi Akuntansi',
                'username' => 'kaprodi.akn',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 47,
                'id_fakultas' => 5,
            ],
            [
                'nama' => 'Kaprodi Hukum',
                'username' => 'kaprodi.fh',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 49,
                'id_fakultas' => 6,
            ],
            [
                'nama' => 'Kaprodi Psikologi',
                'username' => 'kaprodi.psi',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 51,
                'id_fakultas' => 7,
            ],
            [
                'nama' => 'Sekprodi Magister Kenotariatan',
                'username' => 'sekprodi.mk',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 26,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Sekprodi Magister Manajemen',
                'username' => 'sekprodi.mm',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 24,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Sekprod Magister Sains Biomedis',
                'username' => 'sekprodi.msb',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 28,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Sekprodi Magister Administrasi Rumah Sakit',
                'username' => 'sekprodi.mars',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 30,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Sekprodi Doktor Sains Biomedis',
                'username' => 'sekprodi.mars',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 32,
                'id_fakultas' => 1,
            ],
            [
                'nama' => 'Sekprodi Kedokteran',
                'username' => 'sekprodi.fk',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 34,
                'id_fakultas' => 2,
            ],
            [
                'nama' => 'Sekprodi Pendidikan Profesi Dokter',
                'username' => 'sekprodi.fk',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 36,
                'id_fakultas' => 2,
            ],
            [
                'nama' => 'Sekprodi Kedokteran Gigi',
                'username' => 'sekprodi.fkg',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 38,
                'id_fakultas' => 3,
            ],
            [
                'nama' => 'Sekprodi Kedokteran Gigi Program Profesi',
                'username' => 'sekprodi.fkg',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 40,
                'id_fakultas' => 3,
            ],
            [
                'nama' => 'Sekprodi Teknik Informatika',
                'username' => 'sekprodi.ti',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 42,
                'id_fakultas' => 4,
            ],
            [
                'nama' => 'Sekprodi Ilmu Perpustakaan',
                'username' => 'sekprodi.ip',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 44,
                'id_fakultas' => 4,
            ],
            [
                'nama' => 'Sekprodi Manajemen',
                'username' => 'sekprodi.mnj',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 46,
                'id_fakultas' => 5,
            ],
            [
                'nama' => 'Sekprodi Akuntansi',
                'username' => 'sekprodi.akn',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 48,
                'id_fakultas' => 5,
            ],
            [
                'nama' => 'Sekprodi Hukum',
                'username' => 'sekprodi.fh',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 50,
                'id_fakultas' => 6,
            ],
            [
                'nama' => 'Sekprodi Psikologi',
                'username' => 'sekprodi.psi',
                'password' => bcrypt('12345'),
                'role' => 'Prodi',
                'id_jabatan' => 52,
                'id_fakultas' => 7,
            ],

        ];

        foreach ($user as $key => $value) {
            User::create($value);
        }
    }
}
